from kivy.utils import get_color_from_hex

light_colourScheme = {
    "primary": "#725C0C",
    "onPrimary": "#FFFFFF",
    "primaryContainer": "#FFE086",
    "onPrimaryContainer": "#574500",
    "secondary": "#685E3F",
    "onSecondary": "#FFFFFF",
    "secondaryContainer": "#F1E1BB",
    "onSecondaryContainer": "#50462A",
    "tertiary": "#46664B",
    "onTertiary": "#FFFFFF",
    "tertiaryContainer": "#C8ECCA",
    "onTertiaryContainer": "#2F4E35",
    "background": "#FFF8F0",
    "onBackground": "#1E1B13",
    "surface": "#FFF8F0",
    "onSurface": "#1E1B13",
    "surfaceVariant": "#EBE2CF",
    "onSurfaceVariant": "#4C4639",
    "outline": "#7D7667",
}

dark_colourScheme = {
    "primary": "#E1C46D",
    "onPrimary": "#3C2F00",
    "primaryContainer": "#574500",
    "onPrimaryContainer": "#FFE086",
    "secondary": "#D4C5A1",
    "onSecondary": "#383016",
    "secondaryContainer": "#50462A",
    "onSecondaryContainer": "#F1E1BB",
    "tertiary": "#ACCFAF",
    "onTertiary": "#183720",
    "tertiaryContainer": "#2F4E35",
    "onTertiaryContainer": "#C8ECCA",
    "background": "#16130B",
    "onBackground": "#EAE2D4",
    "surface": "#16130B",
    "onSurface": "#EAE2D4",
    "surfaceVariant": "#4C4639",
    "onSurfaceVariant": "#CEC6B4",
    "outline": "#979080",
}